package com.nftstudio.nftstudio.engine;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import javax.imageio.ImageIO;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class GeneratorEngine {

    // --- INNER CLASSES FOR JSON METADATA STRUCTURE ---
    // This perfectly matches the official ERC-721 standard for NFTs
    static class NFTMetadata {
        String name;
        String description;
        String image;
        List<Attribute> attributes = new ArrayList<>();
    }

    static class Attribute {
        String trait_type;
        String value;
        public Attribute(String trait_type, String value) {
            this.trait_type = trait_type;
            this.value = value;
        }
    }
    // -------------------------------------------------

    public static void generateCollection(Map<String, List<String>> databaseLayers, int amountToGenerate, String outputDirectory) {
        Random random = new Random();

        List<String> sortedCategories = new ArrayList<>(databaseLayers.keySet());
        Collections.sort(sortedCategories);

        System.out.println("\nStarting generation of " + amountToGenerate + " NFTs...");

        // Setup Gson to make our JSON look neat and readable
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        for (int i = 1; i <= amountToGenerate; i++) {
            try {
                BufferedImage finalImage = new BufferedImage(800, 600, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = finalImage.createGraphics();

                // Create a fresh metadata object for this specific NFT
                NFTMetadata metadata = new NFTMetadata();
                metadata.name = "My Studio NFT #" + i;
                metadata.description = "Generated by NFT Studio";
                metadata.image = "NFT_" + i + ".png"; // Placeholder until uploaded to IPFS

                for (String category : sortedCategories) {
                    List<String> layerPaths = databaseLayers.get(category);

                    if (layerPaths != null && !layerPaths.isEmpty()) {
                        String randomPath = layerPaths.get(random.nextInt(layerPaths.size()));
                        File layerFile = new File(randomPath);

                        if (layerFile.exists() && layerFile.canRead()) {
                            BufferedImage layerImage = ImageIO.read(layerFile);
                            if (layerImage != null) {
                                g2d.drawImage(layerImage, 0, 0, null);

                                // --- METADATA TRACKING ---
                                // 1. Clean the category name (e.g., "1_Background" -> "Background")
                                String cleanCategory = category.replaceAll("^\\d+_", "");

                                // 2. Get the file name without ".png" (e.g., "Red_Hat.png" -> "Red_Hat")
                                String traitName = layerFile.getName().replace(".png", "").replace("_", " ");

                                // 3. Add it to the JSON attributes list
                                metadata.attributes.add(new Attribute(cleanCategory, traitName));
                            }
                        } else {
                            System.out.println("    -> Warning: Missing file: " + randomPath);
                        }
                    }
                }

                g2d.dispose();

                // 1. Save the PNG Image
                File outputImage = new File(outputDirectory, "NFT_" + i + ".png");
                ImageIO.write(finalImage, "png", outputImage);

                // 2. Save the JSON Metadata
                File outputJson = new File(outputDirectory, "NFT_" + i + ".json");
                try (FileWriter writer = new FileWriter(outputJson)) {
                    gson.toJson(metadata, writer);
                }

                System.out.println("Successfully generated: NFT_" + i);

            } catch (IOException e) {
                System.out.println("Error generating NFT #" + i + ": " + e.getMessage());
            }
        }
        System.out.println("Generation Complete!");
    }
}